### ISSUE TITLE
Task desc. for "Patrol A,B,C, then D'

### ISSUE THREAD

**Issue by raeidsaqur** [RodrigoToroIcarte/reward_machines#11]
Hi,
Just wondering whether switching of 'b' and 'd' (basically task is: _patrol a,d,c, then d_) [t4.txt](https://github.com/RodrigoToroIcarte/reward_machines/blob/master/reward_machines/envs/grids/reward_machines/office/t4.txt) was a typo or the intended task?

**Comment by RodrigoToroIcarte** [comment]
Thanks! I just fixed this. I also swapped the locations of B and D in the map so the results are still consistent with the results from the paper :)
